### ISSUE TITLE
Transferring data over socket failed: The client is not connected to a broker. The requested operation is impossible at this point.

### ISSUE THREAD

**Issue by pheelaphong** [php-mqtt/laravel-client#10]
I'm getting the following exception when running below code:

> PhpMqtt \ Client \ Exceptions \ ClientNotConnectedToBrokerException (192)
[192] Transferring data over socket failed: The client is not connected to a broker. The requested operation is impossible at this point.

My code:

```php
public function subDeviceAll(Request $request)
{
    $device = Device::all();
    $dataDevice = [];
    foreach ($device as $key => $value) {
        $data['data_device'] = $value;
        $data['status'] = $this->checkDeviceOnline($value['device_id']);
        $data['power'] = $this->checkDevicePower($value['device_id']);
        $dataDevice[] = $data;
    }
    return response()->json($dataDevice, 200);
}

public function checkDeviceOnline($device_id)
{
    $device = Device::where('device_id', $device_id)->first();
    $mqtt = MQTT::connection();
    $res = '';
    $topic = $device['topic'];

    $mqtt->publish('cmnd/' . $topic . '/POWER', '', 0);
    $mqtt->subscribe('tele/' . $topic . '/LWT', function (string $topic, string $message) use ($mqtt, &$res) {
        $res = $message;
        $mqtt->interrupt();
    }, 0);

    $mqtt->loop(true);
    $mqtt->disconnect();
    return $res;
}

public function checkDevicePower($device_id)
{
    $device = Device::where('device_id', $device_id)->first();
    $mqtt = MQTT::connection();
    $res = '';
    $topic = $device['topic'];

    $mqtt->publish('cmnd/' . $topic . '/POWER', '', 0);
    $mqtt->subscribe('stat/' . $topic . '/POWER', function (string $topic, string $message) use ($mqtt, &$res) {
        $res = $message;
        $mqtt->interrupt();
    }, 0);
    $mqtt->loop(true);
    $mqtt->disconnect();
    return $res;
}
```

**Comment by Namoshek** [comment]
I think it is because you are calling `$mqtt->disconnect()` in both methods. The `ConnectionManager` (which is what is used behind the `MQTT` facade) does not know that you are disconnecting and will not call `connect()` for you the second time.

My advice would be to remove both calls to `$mqtt->disconnect()` and add one single call to `MQTT::disconnect()` before returning the response.

**Comment by pheelaphong** [comment]
**Thank you very much** im remove $mqtt->disconnect(); all

But Somtime return message empty

> [
{
device_id: 10000,
status: "Online",
power: "OFF"
},
{
device_id: 10001,
status: "Online",
power: "OFF"
},
{
device_id: 10002,
status: "Online",
power: ""
},
{
device_id: 10003,
status: "",
power: ""
},
{
device_id: 10004,
status: "",
power: ""
}
]

My code now

> 
    public function subDeviceAll(Request $request)
    {
        $device = Device::all();
        $dataDevice = [];
        foreach ($device as $key => $value) {
            //$data['data_device'] = $value;
            $data['device_id'] = $value['device_id'];
            $data['status'] = $this->checkDeviceOnline($value['device_id']);
            $data['power'] = $this->checkDevicePower($value['device_id']);
            $dataDevice[] = $data;
        }
        return response()->json($dataDevice, 200);
    }

    public function checkDeviceOnline($device_id)
    {
        $device = Device::where('device_id', $device_id)->first();
        $mqtt = MQTT::connection();
        $res = '';
        $topic = $device['topic'];

        $mqtt->publish('cmnd/' . $topic . '/POWER', '', 2);
        $mqtt->subscribe('tele/' . $topic . '/LWT', function (string $topic, string $message) use ($mqtt, &$res) {
            $res = $message;
            $mqtt->interrupt();
        }, 1);

        $mqtt->loop(true);
        return $res;
    }

    public function checkDevicePower($device_id)
    {
        $device = Device::where('device_id', $device_id)->first();
        $mqtt = MQTT::connection();
        $res = '';
        $topic = $device['topic'];

        $mqtt->publish('cmnd/' . $topic . '/POWER', '', 2);
        $mqtt->subscribe('stat/' . $topic . '/POWER', function (string $topic, string $message) use ($mqtt, &$res) {
            $res = $message;
            $mqtt->interrupt();
        }, 1);
        $mqtt->loop(true);
        return $res;
    }

**Comment by Namoshek** [comment]
Well, that has nothing to do with the library but your devices. I cannot help you with that part.

**Comment by srajiv9496** [comment]
### I'm getting the same error when trying to save the data into my database for future refrences:

 PhpMqtt\Client\Exceptions\ClientNotConnectedToBrokerException 

  [192] Transferring data over socket failed: The client is not connected to a broker. The requested operation is impossible at this point.

  at vendor/php-mqtt/client/src/MqttClient.php:471
    467▕      */
    468▕     protected function ensureConnected(): void
    469▕     {
    470▕         if (!$this->isConnected()) {
  ➜ 471▕             throw new ClientNotConnectedToBrokerException(
    472▕                 'The client is not connected to a broker. The requested operation is impossible at this point.'
    473▕             );
    474▕         }
    475▕     }

      +1 vendor frames 

  2   app/Console/Commands/MqttSubscriber.php:72
      PhpMqtt\Client\MqttClient::disconnect()
      +12 vendor frames 

  15  artisan:35
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))


_Here is my Code._

`
<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use PhpMqtt\Client\Exceptions\MqttClientException;
use PhpMqtt\Client\MqttClient;
use PhpMqtt\Client\ConnectionSettings;
use App\Models\SensorData;

class MqttSubscriber extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'mqtt:subscribe';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Subscribe to an MQTT topic and process messages.';

    /**
     * Execute the console command.
     *
     * @return int
     */
    public function handle()
    {
        $port = env('MQTT_PORT', 1883);
        $topic = env('MQTT_TOPIC', 'v1/sensor-tag/800350/telemetry');
        $tls = filter_var(env('MQTT_TLS', false), FILTER_VALIDATE_BOOLEAN);

        $clientId = uniqid('mqtt_', true);

        $connectionSettings = (new ConnectionSettings)
            ->setKeepAliveInterval(60)
            ->setConnectTimeout(3)
            ->setUseTls($tls)
            ->setTlsSelfSignedAllowed(true);

        $mqtt = new MqttClient($server, $port, $clientId, MqttClient::MQTT_3_1_1);

        try {
            $mqtt->connect($connectionSettings, true);
            $this->info('Connected to MQTT broker.');

            $mqtt->subscribe($topic, function ($topic, $message) {
                $this->info("Received message on topic [$topic]: $message");

                $data = json_decode($message, true);

                if (isset($data['temperature'], $data['humidity'])) {
                    SensorData::create([
                        'sensor_id' => '800350',
                        'temperature' => $data['temperature'],
                        'humidity' => $data['humidity'],
                    ]);
                    $this->info('Data saved to database.');
                }
            }, 0);

            $mqtt->loop(true);
        } catch (MqttClientException $e) {
            $this->error('MQTT Client Error: ' . $e->getMessage());
        } finally {
            $mqtt->disconnect();
            $this->info('Disconnected from MQTT broker.');
        }

        return 0;
    }
}

`

I have not shared the server link here btw. Do ignore that.

**Comment by srajiv9496** [comment]
I'm facing a similar type of issue while taking darta from the sensor.

MQTT Client Error: [1000] Establishing a connection to the MQTT broker failed: Socket error [0]: php_network_getaddresses: getaddrinfo for mqtt.geniusvision.in failed: Try again

   PhpMqtt\Client\Exceptions\ClientNotConnectedToBrokerException 


My Code:

`
class MqttSubscriber extends Command
{
    protected $signature = 'mqtt:subscribe';
    protected $description = 'Subscribe to an MQTT topic and process messages.';

    public function handle()
    {
        $server = env('MQTT_SERVER', 'mqtt.geniusvision.in');
        $port = env('MQTT_PORT', 1883);
        $topic = env('MQTT_TOPIC', 'v1/sensor-tag/800350/telemetry');
        $tls = filter_var(env('MQTT_TLS', false), FILTER_VALIDATE_BOOLEAN);

        $clientId = uniqid('mqtt_', true);

        $connectionSettings = (new ConnectionSettings)
            ->setKeepAliveInterval(60)
            ->setConnectTimeout(3)
            ->setUseTls($tls)
            ->setTlsSelfSignedAllowed(true);

        $mqtt = new MqttClient($server, $port, $clientId, MqttClient::MQTT_3_1_1);

        try {
            $mqtt->connect($connectionSettings, true);
            $this->info('Connected to MQTT broker.');

            $mqtt->subscribe($topic, function ($topic, $message) {
                $this->info("Received message on topic [$topic]: $message");

                $data = json_decode($message, true);

                if (isset($data['temperature'], $data['humidity'])) {
                    SensorData::create([
                        'sensor_id' => '800350',
                        'temperature' => $data['temperature'],
                        'humidity' => $data['humidity'],
                    ]);
                    $this->info('Data saved to database.');
                }
            }, 0);

            $mqtt->loop(true);
        } catch (MqttClientException $e) {
            $this->error('MQTT Client Error: ' . $e->getMessage());
        } finally {
            $mqtt->disconnect();
            $this->info('Disconnected from MQTT broker.');
        }

        return 0;
    }
`

**Comment by Namoshek** [comment]
@srajiv9496 It is not a similar issue. Your device (where this command is run) cannot resolve the host `mqtt.geniusvision.in`. It is a DNS or firewall issue. If you cannot resolve this host using `nslookup` on the same host, this is what you've to look into. It has nothing to do with the MQTT client.
