### ISSUE TITLE
Set ClientD in connection

### ISSUE THREAD

**Issue by icecodex** [php-mqtt/laravel-client#15]
Hi.
How we can set ClientID when create connection ? I want pass dynamic ClientID per connection

Thank you

**Comment by Namoshek** [comment]
When you want to use a specific client id for your connection(s), you can either configure one in the `config/mqtt-client.php`:
https://github.com/php-mqtt/laravel-client/blob/9e69fb1e45b12b3945eea439d718564d0693f141/config/mqtt-client.php#L44-L46

Or you use the base package [`php-mqtt/client`](https://github.com/php-mqtt/client) directly.

This package here is a pure convenience wrapper around the base package which adds configurability via the Laravel framework at the price of flexibility. Use it if you have a simple use case, like one connection or maybe two, one for reads and one for writes. But do not use it when you need a user-configured connection (e.g. where details are stored in the database); it is doable but a pain and error prone.
