### ISSUE TITLE
Setting timeout for subscription

### ISSUE THREAD

**Issue by Ni7r0g3n** [php-mqtt/laravel-client#16]
Hi, I have a controller in where I need to send a message over the socket, wait for an acknowledge and if the ack doesn't arrive in 10 or so seconds it interrupts the connection and prints something. 

I tried this way:
```
$mqtt = MQTT::connection();
        $mqtt->subscribe('/device/'.$serial, function ($topic, $message) use ($mqtt, $rele, $device, $CID) {
            $message = json_decode($message);
            if ($message->msg == 'ACK' && $message->CID == $CID){
                Log::info('ACK Received');
                if($device->getReleStatus($rele)==0) $device->setReleStatus($rele,1);
                else $device->setReleStatus($rele,0);
                $device->save();
            }
            $mqtt->interrupt();
        });
        $mqtt->publish('/device/'.$serial, json_encode($msg));
        $mqtt->loop(true);
        $mqtt->disconnect();
```
I found the socket timeout options inside the configuration file, but I'm not sure it is what i'm looking for as the connection stays open (and the request to the controller hangs forever).
Is this possible or do I have to find a workaround?

**Comment by Ni7r0g3n** [comment]
Found the solution on the other Repo from the author. For short:

```
$mqtt->registerLoopEventHandler(function ($mqtt, float $elapsedTime) {
            if ($elapsedTime >= 10) {
                $mqtt->interrupt();
            }
        });
```

For more info: https://github.com/php-mqtt/client/issues/43#issuecomment-730156396

**Comment by Namoshek** [comment]
Glad you found a solution! I'm open to contributions in the examples repository... 😁

**Comment by Ni7r0g3n** [comment]
> Glad you found a solution! I'm open to contributions in the examples repository... 😁

Gladly, this repo is very useful
