### ISSUE TITLE
Unable to install in Laravel 8 

### ISSUE THREAD

**Issue by sarahalyaat** [php-mqtt/laravel-client#17]
this is what the message returns after using composer require php-mqtt/laravel-client :

>  Problem 1
>     - php-mqtt/client[v1.1.0, ..., v1.1.1] require psr/log ^1.1 -> found psr/log[1.1.0, ..., 1.1.4] but the package is fixed to 2.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
>     - Root composer.json requires php-mqtt/client ^1.1 -> satisfiable by php-mqtt/client[v1.1.0, v1.1.1].

**Comment by Namoshek** [comment]
I'm open to pull requests. This needs to be changed in the base package [`php-mqtt/client`](https://github.com/php-mqtt/client) though. Based on the [diff of `psr/log`](https://github.com/php-fig/log/compare/1.1.4..3.0.0), support should be straight forward and not an issue.

**Comment by Namoshek** [comment]
Support for v2 of `psr/log` has been added in [`v1.1.2` of `php-mqtt/client`](https://github.com/php-mqtt/client/releases/tag/v1.1.2).
