### ISSUE TITLE
accessing web when doing a loop

### ISSUE THREAD

**Issue by ioiofadhil** [php-mqtt/laravel-client#20]
Hi, First, i want to say thank you for making this package. it helps me so much as a laravel dev.

my question is, "is it possible to make the laravel can be accessed while doing a loop?"

what i was trying to do is, keep subscribing the mqtt, post each of the subs to database, and accessing another page at the same time (i was planning to create a log dashboard in another page for a user).
but when im doing a loop, the laravel keep load the loop and make the other page (which is the log dashboard) can't be accessed. it does a infinite load.

my controller is : 
```
    public function mqtt()
    {
        $mqtt = MQTT::connection();

        // Register a hook which is called once per loop and which interrupts the loop after some time.
        // $mqtt->registerLoopEventHandler(function (MqttClient $mqtt, float $elapsedTime) {
        //     if ($elapsedTime >= 40) {
        //         $mqtt->interrupt();
        //     }
        // });

        // subscribe
        $mqtt->subscribe('#', function (string $topic, string $message) use ($mqtt, &$result) {
            $json = json_decode($message, true);
            ModelOne::insert($json);
        }, 0);
        $mqtt->loop(true);
    }
```

is it possible? thank you

**Comment by Namoshek** [comment]
Hi there, glad you like the package and find it useful.

I understand your question, but I have to tell you that your current approach, where the subscription is made within a controller, will not work as expected. By default, PHP requests are limited to 30 seconds of execution time and require a client to keep the connection to the server open, to prevent the request from being aborted. To keep the connection between client and server open, you will also need to ensure proper connection timeouts are in place. All in all, using such subscriptions is bad application design and is not how you would implement it in Laravel.

Instead, you should perform subscriptions within a [console command](https://laravel.com/docs/8.x/artisan). The command can be started (and restarted in case of a crash) by something like [supervisor](https://laravel.com/docs/8.x/queues#supervisor-configuration) (this article is for the `queue:work` command, but works similar for other commands).

By using a command, the data collection runs entirely as daemon on the server and does not require a client (i.e. web browser) to be open at all. In such case, you can then implement the dashboard which displays the collected data in a controller.

**Comment by ioiofadhil** [comment]
i see, understandable. Supervisor the queue looks convicing. Thank you for the reply ! Have a great day !

**Comment by MCKevmeister** [comment]
Running  ```$mqtt->loop()``` anywhere, even in a artisan command causes the program to hang. Supervisor only ensures that the script is kept running, but if it won't finish then it is unable to do anything? 

I've tried to follow the examples in examples repo but all of the subscription examples close the connection which won't keep the subscription connection open.

I'm not sure how to make the daemon run in laravel when the loop function is called without it blocking the laravel application

**Comment by Namoshek** [comment]
The whole point of the `$mqtt->loop()` method is that it is blocking. It is an event loop, which means it does the following things over and over again:
- Read incoming data from the MQTT broker
- Process and deliver the received data to subscription callbacks
  (i.e. the function you register with `$mqtt->subscribe($topic, $callback)`)
- Send outgoing data (published messages, retries, etc.) to the MQTT broker

Because `$mqtt->loop()` is blocking and intended to be run _forever_, it is not recommended to run this method in a controller during a request. It should only be called in a console command where the process is able to run _forever_.

For console commands, the [`ext_pcntl` example](https://github.com/php-mqtt/client-examples/blob/1858fda6cb82def7c111ebdd326022e48653990f/05_interuppting_the_loop/01_use_pcntl_signal_to_interrupt_the_loop.php) is the most suitable. Just remove line 41 and you are good to go. If you wonder what it does:
- It registers a signal handler for `SIGINT` (ctrl + c) which interrupts the `$mqtt->loop()` if running
- It connects to the MQTT broker and subscribes to a topic, then infinitely runs using `$mqtt->loop()` according to above description
- It disconnects gracefully after being interrupted via a `SIGINT` signal

Please be aware that `ext_pcntl` only works on Linux.

**Comment by Sididi** [comment]
> Hi there, glad you like the package and find it useful.
> 
> I understand your question, but I have to tell you that your current approach, where the subscription is made within a controller, will not work as expected. By default, PHP requests are limited to 30 seconds of execution time and require a client to keep the connection to the server open, to prevent the request from being aborted. To keep the connection between client and server open, you will also need to ensure proper connection timeouts are in place. All in all, using such subscriptions is bad application design and is not how you would implement it in Laravel.
> 
> Instead, you should perform subscriptions within a [console command](https://laravel.com/docs/8.x/artisan). The command can be started (and restarted in case of a crash) by something like [supervisor](https://laravel.com/docs/8.x/queues#supervisor-configuration) (this article is for the `queue:work` command, but works similar for other commands).
> 
> By using a command, the data collection runs entirely as daemon on the server and does not require a client (i.e. web browser) to be open at all. In such case, you can then implement the dashboard which displays the collected data in a controller.

Hi Namoshek,

Currently doing something pretty similar, I have a simple artisan command initializing connection and running the infinite loop so it handles subscriptions / sent messages (all in QoS 2)

```php
<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Contracts\Console\Isolatable;

use PhpMqtt\Client\Facades\MQTT;

class RunMQTTLoop extends Command implements Isolatable
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'mqtt:start';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Starts a loop handling all MQTT events';

    /**
     * Determine when an isolation lock expires for the command.
     *
     * @return \DateTimeInterface|\DateInterval
     */
    public function isolationLockExpiresAt()
    {
        return now();
    }

    /**
     * Execute the console command.
     *
     * @return mixed
     */
    public function handle()
    {
        /** @var \PhpMqtt\Client\Contracts\MqttClient $mqtt */
        $this->info('Connecting to MQTT broker...');
        $mqtt = MQTT::connection();

        $this->info('Connected. Now initializing loop.');
        $mqtt->loop();

        return Command::SUCCESS;
    }
}
```

But I would like to access that instance of php-mqtt ($mqtt variable) **outside** of my artisan command so I can use it to send messages and register new subscription channels interactively
By any chance, have you any idea how to properly do it in Laravel? Many thanks

**Comment by Sididi** [comment]
Thank you for the fast answer Namoshek
I wanted to do it this way precisely to avoid opening a connection on each request as I will possibly have several dozens publish per second (each independant)

**Comment by Namoshek** [comment]
Alright, this makes sense (and is also a good thing to avoid). In this case, there are two quite common options:

1. You can create a queued job for each message to publish. There will be one MQTT client per queue worker, so the number is easily calculatable.
    - Pros: Easy to develop and within the Laravel best practices
    - Cons: If you publish messages infrequently, the MQTT client will lose its connection regularly

2. You can build your own _MQTT publish queue worker_ which fetches new messages to publish from a queue and publishes them within a loop. Something like this (please be aware this has intentionally no error handling, etc.):
    ```php
    $mqtt = MQTT::connection();
    $mqtt->registerLoopEventHandler(function (MqttClient $mqtt, float $elapsedTime) {
        $nextMessage = \Redis::lpop('mqtt-messages-to-publish');
        if ($nextMessage === null) {
            // TODO: maybe sleep for a bit to avoid polling Redis too fast
            return;
        }

        $message = json_decode($nextMessage);
        $mqtt->publish($message->topic, $message->content, $message->qos, $message->retain);
    });

    $mqtt->loop(true);
    ```

    - Pros: The MQTT connection will be kept open (via ping/pong) and you have full control over the number of workers/connections
    - Cons: More effort to develop, although not by much
