### ISSUE TITLE
Can not transfer data bigger than 1MB

### ISSUE THREAD

**Issue by SkyZySR** [php-mqtt/laravel-client#25]
I got this error when trying to send data over 1MB [65] Transferring data over socket failed: Sending data over the socket failed. Has it been closed?

**Comment by Namoshek** [comment]
Are you trying to publish over 1MB to the broker or receive 1MB via subscription? To me, this sounds like a sane default broker setting and something you need to change on the broker.

**Comment by SkyZySR** [comment]
> Are you trying to publish over 1MB to the broker or receive 1MB via subscription? To me, this sounds like a sane default broker setting and something you need to change on the broker.
I send base64 image  encode string that size over 1MB to broker from laravel I got error. But I can send base64 image from with bigger size from MQTT app to the same broker it working fine. So, I don't think it is problem with broker.

**Comment by Namoshek** [comment]
What broker are you using? And what client is subscribing to the images?

**Comment by SkyZySR** [comment]
I'm using mosquitto broker.

**Comment by Namoshek** [comment]
With Mosquitto 1.6, I cannot reproduce the issue. I'll try it with Mosquitto 2 when I find the time.

**Comment by edo2313** [comment]
Any news on this? Having th same problem...

**Comment by Namoshek** [comment]
No, since the author of the issue closed it, I did not further investigate this with Mosquitto 2. But since it works with Mosquitto 1.6, I'm pretty confident that it is a configuration issue with Mosquitto and not a bug in this library.
