### ISSUE TITLE
Websocket port

### ISSUE THREAD

**Issue by MalekDekwin** [php-mqtt/laravel-client#33]
how can i change web socket port
this is public server i use it work 
Broker: broker.hivemq.com
TCP Port: 1883
Websocket Port: 8000
now i need to change it to private but it have another websocket port its 8884 how can i change this from code

**Comment by Namoshek** [comment]
This client does not support connecting to MQTT brokers via WebSockets. Only TCP and TCP/TLS is supported.

**Comment by MalekDekwin** [comment]
i have another problem in the web host i got this  : {"host":"broker.hivemq.com","port":1883,"clientId":"55a09cc27f5849a1f1f4","connectionString":"tcp://broker.hivemq.com:1883","error":"Connection refused","code":111}

**Comment by Namoshek** [comment]
What other options are you using besides the `host` and `port`? I have no issues connecting to the broker with said connection string. Is it possible that your firewall is blocking the outgoing connection?
