### ISSUE TITLE
Can the client publish messages on two different ports (TCP and WebSockets)?

### ISSUE THREAD

**Issue by vinaye42** [php-mqtt/laravel-client#34]
`
can we publish topic on two different port:
Tcp Port: 1883,
Websocket Port: 8000 
`

**Comment by Namoshek** [comment]
No, this library does not support WebSockets. I'm not sure your request makes much sense though as a broker which supports both options, TCP and WebSockets, will forward messages regardless of the port and protocol used for publishing.
