### ISSUE TITLE
Support for Laravel 10

### ISSUE THREAD

**Issue by Zakini** [php-mqtt/laravel-client#38]
I can see @Namoshek's already done some work to support [Laravel 10](https://github.com/php-mqtt/laravel-client/commit/c42ec1d6fff0d147c5d552f1ffe93413dd5d5ec1) and [PHP 8.2](https://github.com/php-mqtt/laravel-client/commit/936ce0549d4ca5daf2b478f411c45f2496a5c91b), so just wanted to add an issue to track this.

I've got a new-ish project that uses this package and Laravel 9 that I'm keen to upgrade to Laravel 10. Let me know if there's anything I can do to help!

**Comment by Namoshek** [comment]
There's nothing left to do for Laravel 10 support. I simply forgot to publish a release. Just did so in [`v1.2.0`](https://github.com/php-mqtt/laravel-client/releases/tag/v1.2.0). Sorry! 😅

**Comment by Zakini** [comment]
Amazing! Cheers for sorting that so quickly!
