### ISSUE TITLE
subscribe not working

### ISSUE THREAD

**Issue by pheelaphong** [php-mqtt/laravel-client#4]
******************
```
$mqtt = MQTT::connection();
$mqtt->subscribe('stat/xxxxxxxx/POWER', function (string $topic, string $message) {
        return response()->json(['topic' => $topic, 'message' => $message], 200);
}, 0);
```
**return  empty** 
******************
But on MQTT Dashboard (App android) this topic  working
And publish working

**Comment by Namoshek** [comment]
Before I tell you what's wrong, let me tell you that what you are trying to do, doesn't make much sense. Waiting within a request on a published message will block the request. It can be done, but it is a bad idea.

To focus on the problem: you are returning a response from the subscription callback, which is discarded (the `MqttClient` expects no return value from the closure). You also have not called `$mqtt->loop()`, which is required for a subscription. A working example would be:
```php
$result = [];

$mqtt = MQTT::connection();
$mqtt->subscribe('stat/xxxxxxxx/POWER', function (string $topic, string $message) use ($mqtt, &$result) {
    $result['topic'] = $topic;
    $result['message'] = $message;

    $mqtt->interrupt();
}, 0);
$mqtt->loop(true);

return response()->json($result, 200);
```

---

But I repeat myself: this makes no sense. You should not be waiting for published messages in a request. Most `php-fpm` deployments are configured with a fixed number of workers, which means the whole application will already be unreachable after 10 concurrent requests or so. If you need to process incoming data, use a console command for it.

**Comment by pheelaphong** [comment]
> Before I tell you what's wrong, let me tell you that what you are trying to do, doesn't make much sense. Waiting within a request on a published message will block the request. It can be done, but it is a bad idea.
> 
> To focus on the problem: you are returning a response from the subscription callback, which is discarded (the `MqttClient` expects no return value from the closure). You also have not called `$mqtt->loop()`, which is required for a subscription. A working example would be:
> 
> ```
> $result = [];
> 
> $mqtt = MQTT::connection();
> $mqtt->subscribe('stat/xxxxxxxx/POWER', function (string $topic, string $message) use ($mqtt, &$result) {
>     $result['topic'] = $topic;
>     $result['message'] = $message;
> 
>     $mqtt->interrupt();
> }, 0);
> $mqtt->loop(true);
> 
> return response()->json($result, 200);
> ```
> 
> But I repeat myself: this makes no sense. You should not be waiting for published messages in a request. Most `php-fpm` deployments are configured with a fixed number of workers, which means the whole application will already be unreachable after 10 concurrent requests or so. If you need to process incoming data, use a console command for it.

### Working, Thank you for your advice.
