### ISSUE TITLE
How do you reset the command under supervisor when something changes in controller?

### ISSUE THREAD

**Issue by ioiofadhil** [php-mqtt/laravel-client#44]
Hi, I'm trying to do subscribe where I call `Device` model inside my console command.

```
    public function handle()
    {
        $mqtt = MQTT::connection();
        foreach (Device::all() as $device) {
            $mqtt->subscribe($device->subscribe_topic, function (string $topic, string $message) use ($device) {
                echo "Received message on topic: {$topic}\n";
                echo "Received message with payload: {$message}\n";
            }, 0);
        }
        $mqtt->loop(true);
    }
```

But I want it to dynamically change when New Device is added inside the controllers. What's the best approach to make it happen?

**Comment by Namoshek** [comment]
You could use a loop event handler to load the desired subscriptions from the database (or wherever you store them) and compare them to the active subscriptions. The diff can then be used to remove/add subscriptions.

Just don't run this logic every time the loop event handler runs, that's way too often (multiple times a second) and would potentially impact your MQTT logic negatively. Instead, add some logic that this happens only periodically (e.g. every 60 seconds).

Please also be aware that this will not scale infinitely and scalability really depends on your workload and throughput. If you have a lot of subscriptions, you'll need some kind of sharding (i.e. a way to split subscriptions between workers).

**Comment by ioiofadhil** [comment]
I found the behavior that whenever I use `MQTT::connection();`, it's disconnecting the CLI progress (Supervisor in this case). I often call that function to publish & subscribe to topic whenever new device added with new topics. Good thing is supervisor can run auto restart whenever it happens. But does it really good to be happen that way? Are there any side effects?
