### ISSUE TITLE
plans to support php-mqtt client v2.0?

### ISSUE THREAD

**Issue by wivaku** [php-mqtt/laravel-client#47]
https://github.com/php-mqtt/client recently released v2.0

**Comment by Namoshek** [comment]
No problem, I simply forgot about it in the moment. Released as [`v1.4.0`](https://github.com/php-mqtt/laravel-client/releases/tag/v1.4.0).

Please be aware that you need PHP 8 for the v2 to be used.

**Comment by wivaku** [comment]
that was fast, thanks!
