### ISSUE TITLE
Cannot dispatch job inside subscribe closure

### ISSUE THREAD

**Issue by alex-r-redfern** [php-mqtt/laravel-client#50]
Hi there,

Calling a Job inside the subscribe callback seems to segfault as the call just ends with nothing in the logs other than exceptions within docker.
In this instance the setup and loop are in an artisan command.
```
$mqtt = MQTT::connection();
$mqtt->subscribe('test/+', function (string $topic, string $message) {
    $this->info("Received message on topic {$topic}");
    HandleMqttMessage::dispatch($topic, $message);
    $this->info("Complete");
}, 1);
```
In this instance, the "Complete" message is never reached.

Laravel 10
PHP 8.2
Tried both `redis` and `sync` QUEUE_CONNECTION

Any suggestions would be much appreciated :)

**Comment by Namoshek** [comment]
Using the `sync` queue driver is a bad idea in this case as it will run the job during execution of the MQTT client which can cause a lot of different issues, especially timeouts.

The `redis` driver however should work and I'm not sure why it doesn''t. I've not been using the MQTT client with Laravel for quite some time, so I don't have a suitable test setup right now. Maybe you can 1) provide the full code (Artisan command and job) as well as 2) try to dispatch the job differently: `Bus::dispatch(new HandleMqttMessage($topic, $message))`. If I'm not wrong, dispatching the way you did will only dispatch the job on disposal and that might be an issue here.

By the way, how many messages are you processing at this time?
