### ISSUE TITLE
Unsubscribe

### ISSUE THREAD

**Issue by alprde** [php-mqtt/laravel-client#55]
Hi. How can i unsubscribe from channel?

`
$mqtt = MQTT::connection();
$mqtt->unsubscribe('mergen/2/sync');
$mqtt->disconnect();
`

this code not working. I'm using laravel 10.

**Comment by Namoshek** [comment]
Unsubscribing makes only sense when you subscribed on the same connection earlier. How do you currently know it doesn't work?

**Comment by alprde** [comment]
```php
$mqtt = MQTT::connection();
        $mqtt->subscribe('mergen/2/sync', function ($topic, $message) {
            MqttLog::create([
                "channel" => $topic,
                "message" => $message
            ]);
            }, 0);
        $mqtt->loop(true);
```

I'm subscribing with this code. my device sending hearbit every 30 seconds to me. than i creatind database record. i want unscribing but this code not working.

**Comment by Namoshek** [comment]
```php
$mqtt->loop(true);
```
creates an infinite loop which does not exit by itself. This means that whatever code you put after it, will not be reached unless you put an `$mqtt->interrupt()` call inside an event handler or a subscription callback.

However, you can also unsubscribe in a subscription callback. In other words, stop listening for heartbeats when a heartbeat is received:

```php
$mqtt = MQTT::connection();
$mqtt->subscribe('mergen/2/sync', function ($topic, $message) use ($mqtt) {
    $mqtt->unsubscribe('mergen/2/sync');
}, 0);
$mqtt->loop(true);

// This code is never reached by itself.
$mqtt->disconnect();
```

or alternatively, interrupt the loop:

```php
$mqtt = MQTT::connection();
$mqtt->subscribe('mergen/2/sync', function ($topic, $message) use ($mqtt) {
    $mqtt->interrupt();
}, 0);
$mqtt->loop(true);

// Now this code is reached after receiving the first message on 'mergen/2/sync'.
$mqtt->unsubscribe('mergen/2/sync');
$mqtt->disconnect();
```

**Comment by alprde** [comment]
Thank you for your answer. I was trying this code. Subscription is working but unsubscribe not working.

```php
public function subscribe()
{
    $mqtt = MQTT::connection();
    $mqtt->subscribe('mergen/2/sync', function ($topic, $message) {
        MqttLog::create([
            "channel" => $topic,
            "message" => $message
        ]);
        }, 0);
    $mqtt->loop(true);
}

public function unsubscribe()
{
    $mqtt = MQTT::connection();
    $mqtt->subscribe('mergen/2/sync', function ($topic, $message) use ($mqtt) {
        $mqtt->unsubscribe('mergen/2/sync');
    }, 0);
    $mqtt->loop(true);
}
```
