### ISSUE TITLE
Do you can add php 7.3 as support?

### ISSUE THREAD

**Issue by ssheduardo** [php-mqtt/laravel-client#6]
Hi, 
First thanks for you great job, I have laravel 5.7 and my server has Php 7.3.
Do you can add support for the versión 7.3 the PHP?

![image](https://user-images.githubusercontent.com/1160138/106267166-8e914b80-6229-11eb-810f-a2275bbb7852.png)

Thanks.

**Comment by Namoshek** [comment]
Hi, the library (and also the base library) is using PHP 7.4 features. It cannot be made available for PHP 7.3 easily. Also the Laravel version of yours is not supported, I'm only supporting the last two major versions. If you really need support for these older versions, you'd have to make and maintain your own fork of the libraries.
