### ISSUE TITLE
problem in publish acknowledgement

### ISSUE THREAD

**Issue by ProgrammingPlanet** [php-mqtt/laravel-client#8]
publishing a message is ok, but what about acknowledgment?

the scenario I want is - 

publish command from laravel client to MQTT broker, which will send a command to esp2866, also the esp8266 device has a response topic, where the output of the command will publish. I want this response to ensure that command executed successfully...

kindly help.....

**Comment by Namoshek** [comment]
Your request hasn't really to do with what is known as _acknowledgement_ in MQTT terms. You are looking for a way to perform a remote procedure call (RPC) via MQTT. The secret to a working RPC call is to subscribe to the response topic before publishing the trigger message. I already [answered to a very similar question](https://github.com/php-mqtt/client/issues/66#issuecomment-766721845) previously. The answer even includes a way to timeout the request. When working with the Laravel wrapper, you can skip the connection part and aquire a connected client using `$client = \PhpMqtt\Client\Facades\MQTT::connection()`.

**Comment by ProgrammingPlanet** [comment]
i didn't get much idea about my problem.

what I want is - 

- send(publish) command for turning a thing on/off from laravel-client when an HTTP request arrives.
- recieve response(of executed command) from another response topic
- send data in the HTTP response back to the browser.

kindly help....
