### ISSUE TITLE
How get data from Hex or Raw when subscribe?

### ISSUE THREAD

**Issue by ssheduardo** [php-mqtt/laravel-client#9]
Hi, 
When create a subscribe in my controller, I get data from json, this is perfect but if I send data Raw o Hex, the result es null why?

![image](https://user-images.githubusercontent.com/1160138/106632745-6170d000-657e-11eb-9276-b36a15a91b6a.png)

This is my controller.

```
public function subscribe()
{
    $topic = 'kitcken/rpi';
    $result = [];

    $mqtt = MQTT::connection();
    $mqtt->subscribe($topic, function (string $topic, string $message) use ($mqtt, &$result) {
        $result['topic'] = $topic;
        $result['message'] = json_decode($message);

        $mqtt->interrupt();
    }, 0);
    $mqtt->loop(true);

    $data = json_encode($result);

    Storage::disk('local')->put('result_mqtt.txt',$data);

    return response()->json($result, 200);
}
```

**Comment by Namoshek** [comment]
I don't understand, where are you sending data?

**Comment by ssheduardo** [comment]
> I don't understand, where are you sending data?

Sorry, the error is me.

I send a text plain (not json) so I converting the text plain to json
`
$result['message'] = json_decode($message);`

So text plain is not json and return null.
